<Project Sdk="Microsoft.NET.Sdk"><ItemGroup><ProjectReference Include="../NetCat.Core/NetCat.Core.csproj" /><ProjectReference Include="../NetCat.Engine/NetCat.Engine.csproj" /></ItemGroup><ItemGroup>
  <PackageReference Include="BouncyCastle.Cryptography" Version="2.6.2" />
</ItemGroup><ItemGroup><EmbeddedResource Include="ReleasePublicKey.hex" LogicalName="NetCat.ReleasePublicKey" /></ItemGroup></Project>
