namespace ServiceLib.Enums;

public enum EViewAction
{
    CloseWindow,
    ShowYesNo,
    SaveFileDialog,
    AddBatchRoutingRulesYesNo,
    SetClipboardData,
    AddServerViaClipboard,
    AddServerViaFile,
    ImportRulesFromClipboard,
    ProfilesFocus,
    ShareSub,
    ShareServer,
    ScanScreenTask,
    ScanImageTask,
    BrowseServer,
    SelectLocalUpdatePackage,
    ImportRulesFromFile,
    InitSettingFont,
    PasswordInput,
    SubEditWindow,
    RoutingRuleSettingWindow,
    RoutingRuleDetailsWindow,
    AddServerWindow,
    AddServer2Window,
    AddGroupServerWindow,
    DNSSettingWindow,
    RoutingSettingWindow,
    OptionSettingWindow,
    FullConfigTemplateWindow,
    GlobalHotkeySettingWindow,
    SubSettingWindow,
    DispatcherRefreshServersBiz,
    DispatcherRefreshIcon,
    DispatcherShowMsg,
}
