using System.Net;
using System.Net.Sockets;
using System.Text;
using NetCat.Core;

namespace NetCat.Network;

// Fixed main-core DNS transports. Native domain-rule reload can lag behind an
// edit: the ordinary-resolver path must synchronously reject the new suffix.
// Corporate resolution still uses the existing authenticated sidecar path.
public sealed class CorporateDnsGuard : IDisposable
{
    private readonly object gate = new();
    private readonly CancellationTokenSource lifetime = new();
    private readonly SemaphoreSlim capacity = new(256);
    private readonly Endpoint direct, vpn;
    public CorporateDomainGuard DomainGuard { get; }

    private sealed class Endpoint(TcpListener tcp, UdpClient udp, int returnPort)
    {
        public TcpListener Tcp { get; } = tcp;
        public UdpClient Udp { get; } = udp;
        public int ReturnPort = returnPort;
        public int Port => ((IPEndPoint)Tcp.LocalEndpoint).Port;
    }
    private readonly HashSet<int> retiredReturns = [];
    public void RestoreReturnPorts(int directPort,int vpnPort)
    { lock(gate) { direct.ReturnPort=directPort;vpn.ReturnPort=vpnPort; } }

    public void ReallocateReturnPorts(params int[] excluded)
    {
        lock (gate)
        {
            retiredReturns.Add(direct.ReturnPort); retiredReturns.Add(vpn.ReturnPort);
            var taken = retiredReturns.Concat(excluded).Append(DirectPort).Append(VpnPort).Select(p => (int?)p).ToArray();
            int nextDirect = PortStartup.Distinct(OpenVpnService.FreeTcpUdpPort, taken);
            int nextVpn = PortStartup.Distinct(OpenVpnService.FreeTcpUdpPort, taken.Append(nextDirect).ToArray());
            direct.ReturnPort = nextDirect; vpn.ReturnPort = nextVpn;
        }
    }

    public int DirectPort => direct.Port;
    public int VpnPort => vpn.Port;
    public int DirectReturnPort => direct.ReturnPort;
    public int VpnReturnPort => vpn.ReturnPort;

    public CorporateDnsGuard(CorporateDomainGuard? domainGuard = null, Func<int>? allocatePort = null, IReadOnlyCollection<int>? excludedPorts = null)
    {
        DomainGuard = domainGuard ?? new();
        var excluded = excludedPorts ?? Array.Empty<int>();
        direct = Bind(allocatePort, excluded);
        try
        {
            vpn = Bind(allocatePort, excluded.Concat([direct.Port, direct.ReturnPort]).ToArray());
        }
        catch
        {
            direct.Tcp.Stop();
            direct.Udp.Dispose();
            throw;
        }
        _ = UdpLoop(direct); _ = UdpLoop(vpn); _ = TcpLoop(direct); _ = TcpLoop(vpn);
    }

    private static Endpoint Bind(Func<int>? allocatePort, IReadOnlyCollection<int> excluded)
    {
        for (int attempt = 0; attempt < 20; attempt++)
        {
            var (tcp, udp) = PortStartup.BindTcpUdp();
            try
            {
                int port = ((IPEndPoint)tcp.LocalEndpoint).Port;
                if(excluded.Contains(port)){tcp.Stop();udp.Dispose();continue;}
                int?[] excludedArray = excluded.Select(x => (int?)x).Concat([(int?)port]).ToArray();
                int returnPort = PortStartup.Distinct(allocatePort ?? OpenVpnService.FreeTcpUdpPort, excludedArray);
                return new(tcp, udp, returnPort);
            }
            catch (SocketException)
            {
                tcp.Stop();
                udp.Dispose();
            }
            catch {tcp.Stop();udp.Dispose();throw;}
        }
        throw new IOException("Не удалось закрепить DNS-защиту OpenVPN.");
    }

    public void Prepare(AppSettings settings)
    {
        lock (gate)
        {
            DomainGuard.Prepare(settings);
        }
    }

    private static string Question(byte[] packet)
    {
        if (packet.Length < 17 || (packet[2] & 0xf8) != 0 || packet[4] != 0 || packet[5] != 1) throw new IOException("Invalid DNS question");
        int position = 12, total = 0; var labels = new List<string>();
        while (true)
        {
            if (position >= packet.Length) throw new IOException("Truncated DNS question");
            int length = packet[position++]; if (length == 0) break;
            // Queries generated by the native resolver have one uncompressed
            // question. Reject pointers/ambiguous forms rather than bypass guard.
            if (length > 63 || position + length > packet.Length || (total += length + 1) > 254) throw new IOException("Invalid DNS name");
            var span = packet.AsSpan(position, length);
            foreach (var value in span) if (value > 127 || value == 0 || value == '.') throw new IOException("Invalid DNS label");
            labels.Add(Encoding.ASCII.GetString(span).ToLowerInvariant()); position += length;
        }
        if (position + 4 > packet.Length) throw new IOException("Truncated DNS type");
        return string.Join('.', labels);
    }

    private static byte[] Refused(byte[] query)
    {
        var result = query.ToArray(); if (result.Length < 12) return [];
        result[2] = (byte)(0x80 | (result[2] & 1)); result[3] = 0x85;
        result[6] = result[7] = result[8] = result[9] = result[10] = result[11] = 0; return result;
    }

    private async Task<byte[]> Resolve(Endpoint endpoint, byte[] query, CancellationToken ct)
    {
        string name;
        try { name = Question(query); } catch (IOException) { return Refused(query); }
        using var upstream = new UdpClient(AddressFamily.InterNetwork); upstream.Connect(IPAddress.Loopback, endpoint.ReturnPort);
        using var deadline = CancellationTokenSource.CreateLinkedTokenSource(ct); deadline.CancelAfter(TimeSpan.FromSeconds(3));
        long started; ValueTask<int> send;
        lock (gate)
        {
            if (DomainGuard.IsCorporate(name)) return Refused(query);
            started = DomainGuard.Revision;
            // Initiating the send and updating domain ownership use one lock.
            send = upstream.SendAsync(query, deadline.Token);
        }
        try
        {
            await send; var response = (await upstream.ReceiveAsync(deadline.Token)).Buffer;
            lock (gate)
            {
                if (started != DomainGuard.Revision && DomainGuard.IsCorporate(name)) return Refused(query);
                if (response.Length < 12 || response[0] != query[0] || response[1] != query[1] || (response[2] & 0x80) == 0) return Refused(query);
                return response;
            }
        }
        catch (Exception e) when (e is SocketException or OperationCanceledException or ObjectDisposedException) { return Refused(query); }
    }

    private async Task UdpLoop(Endpoint endpoint)
    {
        try { while (!lifetime.IsCancellationRequested) { var q = await endpoint.Udp.ReceiveAsync(lifetime.Token); if (!IPAddress.IsLoopback(q.RemoteEndPoint.Address) || !capacity.Wait(0)) continue; _ = AnswerUdp(endpoint, q); } }
        catch (Exception e) when (e is SocketException or OperationCanceledException or ObjectDisposedException) { }
    }

    private async Task AnswerUdp(Endpoint endpoint, UdpReceiveResult q)
    {
        try { var response = await Resolve(endpoint, q.Buffer, lifetime.Token); if (response.Length > 0) await endpoint.Udp.SendAsync(response, q.RemoteEndPoint, lifetime.Token); }
        catch (Exception e) when (e is SocketException or OperationCanceledException or ObjectDisposedException) { }
        finally { capacity.Release(); }
    }

    private async Task TcpLoop(Endpoint endpoint)
    {
        try { while (!lifetime.IsCancellationRequested) { var client = await endpoint.Tcp.AcceptTcpClientAsync(lifetime.Token); if (!capacity.Wait(0)) { client.Dispose(); continue; } _ = AnswerTcp(endpoint, client); } }
        catch (Exception e) when (e is SocketException or OperationCanceledException or ObjectDisposedException) { }
    }

    private async Task AnswerTcp(Endpoint endpoint, TcpClient client)
    {
        using (client)
        using (var timeout = CancellationTokenSource.CreateLinkedTokenSource(lifetime.Token))
        try
        {
            timeout.CancelAfter(TimeSpan.FromSeconds(5)); var stream = client.GetStream(); var prefix = new byte[2];
            await stream.ReadExactlyAsync(prefix, timeout.Token); int length = (prefix[0] << 8) | prefix[1]; if (length < 12) return;
            var query = new byte[length]; await stream.ReadExactlyAsync(query, timeout.Token); var response = await Resolve(endpoint, query, timeout.Token);
            await stream.WriteAsync(new byte[] { (byte)(response.Length >> 8), (byte)response.Length }, timeout.Token); await stream.WriteAsync(response, timeout.Token);
        }
        catch (Exception e) when (e is IOException or SocketException or OperationCanceledException or ObjectDisposedException) { }
        finally { capacity.Release(); }
    }

    private bool disposed;
    public void Dispose()
    {
        lock (gate)
        {
            if (disposed) return;
            disposed = true;
        }
        try { lifetime.Cancel(); } catch (ObjectDisposedException) { }
        try { direct.Tcp.Stop(); } catch { }
        try { vpn.Tcp.Stop(); } catch { }
        direct.Udp.Dispose();
        vpn.Udp.Dispose();
        try { lifetime.Dispose(); } catch (ObjectDisposedException) { }
    }
}
