<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>WinExe</OutputType><UseWPF>true</UseWPF><AssemblyName>NetCat</AssemblyName><ApplicationIcon>Assets/NetCat.ico</ApplicationIcon><ApplicationManifest>app.manifest</ApplicationManifest></PropertyGroup><ItemGroup><Resource Include="Assets/logo.png"/><Resource Include="Assets/NetCat.ico"/><ProjectReference Include="../NetCat.Core/NetCat.Core.csproj" /><ProjectReference Include="../NetCat.Engine/NetCat.Engine.csproj" /><ProjectReference Include="../NetCat.Network/NetCat.Network.csproj" /><ProjectReference Include="../NetCat.Updater/NetCat.Updater.csproj" /><PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" /></ItemGroup></Project>
