// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddWhitelistApp(arg1) {
  return window['go']['main']['App']['AddWhitelistApp'](arg1);
}

export function AddWhitelistDomain(arg1) {
  return window['go']['main']['App']['AddWhitelistDomain'](arg1);
}

export function DisableSystemProxy() {
  return window['go']['main']['App']['DisableSystemProxy']();
}

export function DisableTUNMode() {
  return window['go']['main']['App']['DisableTUNMode']();
}

export function EnableSystemProxy() {
  return window['go']['main']['App']['EnableSystemProxy']();
}

export function EnableTUNMode() {
  return window['go']['main']['App']['EnableTUNMode']();
}

export function GetAvailableConfigs() {
  return window['go']['main']['App']['GetAvailableConfigs']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetTUNModeStatus() {
  return window['go']['main']['App']['GetTUNModeStatus']();
}

export function GetV2RayNProfiles() {
  return window['go']['main']['App']['GetV2RayNProfiles']();
}

export function GetV2RayNProfilesPath() {
  return window['go']['main']['App']['GetV2RayNProfilesPath']();
}

export function GetWhitelistApps() {
  return window['go']['main']['App']['GetWhitelistApps']();
}

export function GetWhitelistDomains() {
  return window['go']['main']['App']['GetWhitelistDomains']();
}

export function GetZapretFiles() {
  return window['go']['main']['App']['GetZapretFiles']();
}

export function ImportVlessLink(arg1) {
  return window['go']['main']['App']['ImportVlessLink'](arg1);
}

export function ParseVlessLink(arg1) {
  return window['go']['main']['App']['ParseVlessLink'](arg1);
}

export function RemoveWhitelistApp(arg1) {
  return window['go']['main']['App']['RemoveWhitelistApp'](arg1);
}

export function RemoveWhitelistDomain(arg1) {
  return window['go']['main']['App']['RemoveWhitelistDomain'](arg1);
}

export function SaveV2RayNProfile(arg1) {
  return window['go']['main']['App']['SaveV2RayNProfile'](arg1);
}

export function SetActiveProfile(arg1) {
  return window['go']['main']['App']['SetActiveProfile'](arg1);
}

export function SetConfig(arg1) {
  return window['go']['main']['App']['SetConfig'](arg1);
}

export function StartV2RayN() {
  return window['go']['main']['App']['StartV2RayN']();
}

export function StartZapret() {
  return window['go']['main']['App']['StartZapret']();
}

export function StopV2RayN() {
  return window['go']['main']['App']['StopV2RayN']();
}

export function StopZapret() {
  return window['go']['main']['App']['StopZapret']();
}

export function TestDiscord() {
  return window['go']['main']['App']['TestDiscord']();
}

export function TestYouTube() {
  return window['go']['main']['App']['TestYouTube']();
}

export function TestZapretConfig(arg1) {
  return window['go']['main']['App']['TestZapretConfig'](arg1);
}

export function UpdateRoutingRules() {
  return window['go']['main']['App']['UpdateRoutingRules']();
}
