// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddWhitelistApp(arg1:string):Promise<void>;

export function AddWhitelistDomain(arg1:string):Promise<void>;

export function DisableSystemProxy():Promise<void>;

export function DisableTUNMode():Promise<void>;

export function EnableSystemProxy():Promise<void>;

export function EnableTUNMode():Promise<void>;

export function GetAvailableConfigs():Promise<Array<Record<string, any>>>;

export function GetStatus():Promise<Record<string, any>>;

export function GetTUNModeStatus():Promise<Record<string, any>>;

export function GetV2RayNProfiles():Promise<Array<Record<string, any>>>;

export function GetV2RayNProfilesPath():Promise<string>;

export function GetWhitelistApps():Promise<Array<Record<string, any>>>;

export function GetWhitelistDomains():Promise<Array<Record<string, any>>>;

export function GetZapretFiles():Promise<Record<string, any>>;

export function ImportVlessLink(arg1:string):Promise<void>;

export function ParseVlessLink(arg1:string):Promise<Record<string, any>>;

export function RemoveWhitelistApp(arg1:string):Promise<void>;

export function RemoveWhitelistDomain(arg1:string):Promise<void>;

export function SaveV2RayNProfile(arg1:main.V2RayNConfig):Promise<void>;

export function SetActiveProfile(arg1:string):Promise<void>;

export function SetConfig(arg1:string):Promise<void>;

export function StartV2RayN():Promise<void>;

export function StartZapret():Promise<void>;

export function StopV2RayN():Promise<void>;

export function StopZapret():Promise<void>;

export function TestDiscord():Promise<Record<string, any>>;

export function TestYouTube():Promise<Record<string, any>>;

export function TestZapretConfig(arg1:string):Promise<Record<string, any>>;

export function UpdateRoutingRules():Promise<void>;
